server:
  error:
    include-stacktrace: on_param

spring:
  application:
    name: spring-completeapp

  h2:
    console:
      enable: true
    path: /h2-console

  datasource:
    platform: h2
    driverClassName: org.h2.Driver
    url: jdbc:h2:mem:testdb;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    username: sa
    password:
    initialization-mode: ALWAYS
#    data: classpath:/db/data.sql

  jpa:
    hibernate:
      ddl-auto: update
  properties:
    hibernate:
      dialect: org.hibernate.dialect.H2Dialect
      format_sql: true
  show-sql: true

  logging:
    level:
      org:
        hibernate:
          SQL: DEBUG

  info:
    app: Complete APP Spring Boot by Andrê Reges
    website: https://github.com/andrereges/
    github: https://github.com/andrereges/spring-completeapp