debug: false

server:
  servlet:
    session:
      tracking-modes: cookie
  error:
    include-stacktrace: on_param

management:
  endpoints:
    web:
      exposure:
        include: info, health, metrics

info:
  app: Complete APP Spring Boot by Andrê Reges
  website: https://github.com/andrereges/
  github: https://github.com/andrereges/spring-completeapp

springdoc:
  swagger-ui.path: /swagger-ui.html
  show-actuator: true

spring:
  application:
    name: spring-completeapp

  profiles:
    active: ${APP_PROFILE:dev}
    include:
      - application-test
      - application-dev
      - application-prod

  logging:
    level:
      org:
        hibernate:
          SQL: DEBUG