debug: false

server:
  servlet:
    session:
      tracking-modes: cookie
  error:
    include-stacktrace: on_param

spring:
  application:
    name: spring-completeapp

  profiles:
    active: ${APP_PROFILE:dev}
    include:
      - application-test
      - application-dev
      - application-prod

  logging:
    level:
      org:
        hibernate:
          SQL: DEBUG

  info:
    app: Complete APP Spring Boot by Andrê Reges
    website: https://github.com/andrereges/
    github: https://github.com/andrereges/spring-completeapp