global:
  scrape_interval:     15s

scrape_configs:
  - job_name: 'spring-complete-app-actuator'
    scrape_interval: 5s
    metrics_path: "/actuator/prometheus"
    static_configs:
      - targets: ['app:8080']